@startuml ClassIUML
page 2x2
skinparam pageMargin 10
skinparam pageExternalColor gray
skinparam pageBorderColor black

!define PHP << (P,orchid) >>

namespace users {
	class admin_page PHP {

	}
	
	class admin_pages PHP {

	}

	namespace classes{

		class Config PHP {
			+get()
		}

		class Cookie PHP {
			+exists()
			+get()
			+put()
			+delete()

		}

		class DB PHP {
			-$_Instance
			-$_pdo
			-$_query
			-$_error
			-$_results
			-$_ResultsArray
			-$_count
			-$_lastId
			-$_queryCount
			-_construct()
			+getInstance()
			+query()
			+findAll()
			+findById()
			+action()
			+get()
			+delete()
			+deleteByID()
			+insert()
			+update()
			+results()
			+first()
			+count()
			+error()
			+lastID()
			+getQueryCount()

			
		}		

		class Hash PHP {
			+make()
			+salt()
			+unique():
		}

		class Input PHP {
			+exists()::boolean
			+get()
			+sanitize()
		}		

		class Redirect PHP {
			+to()
		}			

		class Session PHP {
			+exists()
			+put()
			+delete()
			+get()
			+flash()
			+uagent_no_version()
		}

		package Shuttle_Dumper.php{
			abstract class Shuttle_Dump_File {
				#$fh
				#$file_location
				{abstract}write()
				{abstract}end()
				create()
				__construct()
				is_gzip()
			}

			class Shuttle_Dump_File_Plaintext extends Shuttle_Dump_File {
				+open()
				+write()
				+end()
			}

			class Shuttle_Dump_File_Gzip extends Shuttle_Dump_File{
				+open()
				+write()
				+end()
			}

			class Shuttle_Insert_Statement{
				-$rows
				-$length
				-$table
				__construct()
				reset()
				add_row()
				get_sql()
				get_length()
			}

			abstract class Shuttle_Dumper{
				~INSERT_THRESHOLD
				+$db
				$dump_file
				$eol
				$include_tables
				$exclude_tables
				{static}create()
				__construct()
				{static}has_shell_access()
				{static}is_shell_command_available()
				{abstract}dump()
				~get_tables()
			}

			class Shuttle_Dumper_ShellCommand extends Shuttle_Dumper{
				dump()
			}

			class Shuttle_Dumper_Native extends Shuttle_Dumper{
				dump()
				#dump_table()
			}

			class Shuttle_DBConn{
				+$host
				+$username
				+password
				+$name
				#$connection
				__construct()
				{static} create()
			}

			class Shuttle_DBConn_Mysql extends Shuttle_DBConn{
				connect()
				query()
				fetch_numeric()
				fetch()
				escape()
				escape_like()
				get_var()
				fetch_row()
			}

			class Shuttle_DBConn_Mysqli extends Shuttle_DBConn {
				connect()
				query()
				fetch_numeric()
				fetch()
				escape()
				escape_like()
				get_var()
				fetch_row()
			}

			class Shuttle_Exception extends Exception{ 

			}

		}

		class Token PHP {
			+{static} generate()
			+{static} check()
		}	

		class User PHP {
			-$_db
			-$_data
			-$_sessionName
			-$_isLoggedIn
			-$_cookieName
			+$tableName
			+__construct()
			+create() 
			+find()
			+login()
			+loginEmail()
			+checkUser()
			+exists()
			+data()
			+isLoggedIn()
			+notLoggedInRedirect()
			+logout()
			+update()
			+hasPermission()
			+noPermissionRedirect()


		}			

		class Validate PHP {
			-$_passed
			-$_errors
			-$_db
			+__construct()
			+check()
			+addError()
			+display_errors()
			+errors() >> $this->$_errors
			+passed() >> $this->$_passed
		}		
	'Namespace Classes
	}

	Namespace helpers{
		class audit PHP{
			getIP()
			fetchUserjsonPIE()
			fetchUserjsonLG2()
			fetchUserjsonLG()
			fetchAllLatest($userid,$start,$end,$eventcode)
			countStuff($what)
			countLoginsSince($eventcode,$since)
			ago($time)
			fetchAllAudit()
			fetchUserAudit($userid)
			writeAudit($userid,$userip,$othus,$event,$action,$itemid=0)
		}

		class backup_util PHP{
			csv_to_array($filename='', $delimiter=',')
			recurse_copy($src,$dst)
			zipData($source, $destination)
			rrmdir($src)
			delete_dir($dir) 
			backupObjects($backupItems,$backupPath)
			backupZip($backupPath,$delBackupPath=false)
			backupUsTables($backupPath)
			backupUsTable($backupPath)
			extractZip($restoreFile,$restoreDest)
			importSqlFile($sqlFile)
		}

		class google_helpers  {
	
		}
		google_helpers <. users.src.Google.Google_Client : includes
		google_helpers <. users.src.Google.contrib.Google_Oauth2Service : includes


		class helpers {
			size($path)
			sanitize($string)
			currentPage()
			currentFolder()
			format_date($date,$tz)
			abrev_date($date,$tz)
			money($ugly)
			name_from_id($id)
			display_errors($errors = array())
			display_successes($successes = array())
			email($to,$subject,$body,$attachment=false)
			email_body($template,$options = array())
			inputBlock($type,$label,$id,$divAttr=array(),$inputAttr=array(),$helper='')
			dump($var)
			dnd($var)
			bold($text)
			err($text)
			redirect($location)
			output_message($message)
		}
		helpers <. us_helpers
		helpers <. users_online
		helpers <. language
		helpers <. backup_util	


	'Namepace helpers	
	}

'Namspace Users
}

users.admin_page - users.classes.User

users.classes.User - users.classes.Session

users.admin_pages - users.classes.Session





@enduml