@startuml 

'Begin definitions

!define indexPHP
!define USER
!define accountPHP
!define loginPHP
!define joinPHP
!define headerPHP
!define navigationPHP

'End definitions

!includeurl http://raw.githubusercontent.com/tolgaulas/UserSpiceUML/master/_actors.iuml


user->index: Requests

activate index
    index <- header : included
    index <- navigation: included
  
	alt $user->isLoggedIn() == TRUE
		|||
        index o--> account: LINK
		|||
	else $user->isLoggedIn() != TRUE
 		|||
 		index o--> login :  LINK
        index o--> join : LINK
        |||
  	end
  index->user : Display page

deactivate index

@enduml