@startuml
!includeurl https://raw.githubusercontent.com/tolgaulas/UserSpiceUML/master/_actors.iuml

title users/account.php

'Begin definitions

!define USER
!define accountPHP
!define loginPHP
!define joinPHP
!define headerPHP
!define navigationPHP

'End definitions


user->account : Requests









@enduml