@startuml

title users/login.php

'Begin definitions

!define USER
!define loginPHP
!define initPHP
!define headerPHP
!define navigationPHP
!define recaptcha_configPHP
!define custom_login_scriptPHP
!define google_oauth_loginPHP
!define facebook_oauth_loginPHP
!define page_footerPHP
!define html_footerPHP


'End definitions

!ifdef Local
	!include _actors.iuml
!else
	!includeurl https://raw.githubusercontent.com/tolgaulas/UserSpiceUML/master/_actors.iuml
!endif

note over user 
	This requires rework on the flow logic
end note

user->login : Requests

activate login
	login <- init : included
	login <- header : included
    login <- navigation: included
    group if Input::exists()
      group if $settings->recaptcha == 1
          login <- recaptcha_config : included
      else

      end
      login <-custom_login_script : included

	end

	group if $settings->glogin==1
		login <- google_oauth_login : included
	end

	group if $settings->fblogin==1
		login <- facebook_oauth_login : included
	end 

	login <- page_footer : included
    login <- html_footer : included
    
login->user : Display page
deactivate login


@enduml