@startuml

title users/account.php

'Begin definitions

!define USER
!define accountPHP
!define loginPHP
!define joinPHP
!define headerPHP
!define navigationPHP

'End definitions

!ifdef Local
	!include _actors.iuml
!else
	!includeurl https://raw.githubusercontent.com/tolgaulas/UserSpiceUML/master/_actors.iuml
!endif


user->account : Requests









@enduml