@startuml

!define TITLE "users/login.php"

'Begin definitions

!define USER
!define loginPHP
!define initPHP
!define headerPHP
!define navigationPHP
!define recaptcha_configPHP
!define custom_login_scriptPHP
!define google_oauth_loginPHP
!define facebook_oauth_loginPHP
!define page_footerPHP
!define html_footerPHP

!includeurl https://raw.githubusercontent.com/tolgaulas/UserSpiceUML/master/_actors.iuml
!include _actors.iuml

!define THEPAGE login

'End definitions

note over user 
	This requires rework on the flow logic
end note

user->THEPAGE : Requests

activate THEPAGE
	THEPAGE <- init : included
	THEPAGE <- header : included
    THEPAGE <- navigation: included
    group if Input::exists()
      group if $settings->recaptcha == 1
          THEPAGE <- recaptcha_config : included
      else

      end
      THEPAGE <-custom_login_script : included

	end

	group if $settings->glogin==1
		THEPAGE <- google_oauth_login : included
	end

	group if $settings->fblogin==1
		THEPAGE <- facebook_oauth_login : included
	end 

	THEPAGE <- page_footer : included
    THEPAGE <- html_footer : included
    
THEPAGE->user : Display page
deactivate THEPAGE


@enduml