@startuml
!include _defs.plantuml

'/users/src
Namespace src {

	package Facebook{
	}
	package Google{
	}
'	!include CLASS_users#src#Facebook.plantuml
'	!include CLASS_users#src#Google.plantuml

'Namespace src
}

@enduml